### ISSUE TITLE
7. 출근/퇴근 인증하는 함수

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastleminiproject1#10]

**Comment by Losecow** [comment]
우선 출근인지 퇴근인지 물어보고
사람마다 고유 번호를 주고 번호 입력 후 비밀번호를 입력하는 방식으로 출퇴근을 관리했으면 좋겠어요

**Comment by qlswltjdhandong** [comment]
고유번호를 준다는게 어떤 의미인가요?

**Comment by Losecow** [comment]
자신의 아이디처럼 사용할 수 있는 번호를 의미합니다
예를 들면 회사에서의 자기 자리에 해당하는 번호를 준다거나 하는 방식입니다

**Comment by qlswltjdhandong** [comment]
좋은 거 같아요!!

**Comment by Losecow** [comment]
넵~~!

**Comment by Losecow** [comment]
이 함수가 실행되면 파일 저장 함수도 실행되게 구현했으면 좋겠습니다!!
