### ISSUE TITLE
8. 출근 기록, 퇴근 기록 보는 함수 (log 관리)

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastleminiproject1#11]

**Comment by qlswltjdhandong** [comment]
파일 읽어오는 함수로 받아오고 출력을 하면 될 거 같습니다!!

**Comment by Losecow** [comment]
이름을 검색해서 찾는 방법이 실용적이지 않을까요?

**Comment by qlswltjdhandong** [comment]
그렇겠네요 하나씩 다 찾기에는 비효율적인 거 같은 생각이 드네요!!

**Comment by qlswltjdhandong** [comment]
이름 뿐만이 아니라 직책도 포함시켰으면 좋을 거 같아요!

**Comment by Losecow** [comment]
아 좋은거 같아요!! 그럼 이름이나 직책 등으로 검색해서 정보를 나열하는 방식으로 구현되게 하면 될 것 같아요!
