### ISSUE TITLE
11. 출근하고 퇴근 잘못 찍었을 때 표현해주는 함수

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastleminiproject1#14]

**Comment by Losecow** [comment]
출근/퇴근 인증하는 함수 안에 들어가있는 함수
만약 출근 상태에서 출근을 인증하려 시도할 때(반대의 경우에도) 
> 출근 기록이 있을 때에 이 함수에서 기록 확인 후 "중복된 접근입니다" 와 같은 메세지 표시

**Comment by qlswltjdhandong** [comment]
출근기록을 확인하는 방법은 loaddata함수를 실행을 하고 나서 방금 입력한 비밀번호로 사람을 찾은 뒤에 출근 기록 칸에 정보가 존재한다면 printf로 출력하면 될 거 같아요!

**Comment by Losecow** [comment]
넵 이해했슴다!!
