### ISSUE TITLE
12. 지각한 사람 체크 함수

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastleminiproject1#15]

**Comment by Losecow** [comment]
시간을 비교해서(출근 시간과 현재 출근한 시간) 출근 시간 - 현재 시간이 양수일 경우 지각으로 체크

**Comment by qlswltjdhandong** [comment]
좀 더 정확하게 말하면 분하고 초도 넣어가지고 계산하면 좋을 거 같아여!!

**Comment by Losecow** [comment]
네 좋습니다!!

**Comment by qlswltjdhandong** [comment]
만약에 시간이 음수라면 분하고 초는 안 봐도 될 거 같은데

**Comment by qlswltjdhandong** [comment]
시간이 음수가 아니면 두개를 비교를 해야될 거 같아요!!

**Comment by Losecow** [comment]
그렇네요 !!

**Comment by qlswltjdhandong** [comment]
그래서 시간을 비교하고 만약에 지각이라는 판정이 난다면 그 사람들을 다 출력을 할까요?

**Comment by qlswltjdhandong** [comment]
다 출력하는게 맞는 거 같네요 반복문 써가지고

**Comment by Losecow** [comment]
네 반복문으로 지각인 사람들만 다 골라내면 좋을거같아요
