### ISSUE TITLE
서비스를 구현하기 위해 필요한 함수가 뭐가 있을까요?

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastleminiproject1#3]

**Comment by qlswltjdhandong** [comment]
일단은 출퇴근 시스템이기 때문에 출근 인증하는 함수를 먼저 생각해보면 좋을 거 같아요!!

**Comment by Losecow** [comment]
출근 관련 전체 메뉴를 불러오는 함수도 필요할 것 같습니다

**Comment by Losecow** [comment]
*출근 -> 출퇴근

**Comment by qlswltjdhandong** [comment]
출근한 사람 보는 함수도 필요할 거 같아요

**Comment by Losecow** [comment]
출근 기록 로드 함수 / 퇴근 기록 로드 함수도 필요할 것 같습니다

**Comment by qlswltjdhandong** [comment]
그리고 지각한 사람 보는 함수도 있으면 좋을 거 같아요!!

**Comment by Losecow** [comment]
출근이나 퇴근을 찍고 바로 저장이 되게 하는 함수

**Comment by qlswltjdhandong** [comment]
만약에 외근을 하게 된다면 그거를 표시해주는 함수?(현재 있는 사람들을 보여주면서 현재 상태를 보여줌)

**Comment by Losecow** [comment]
그 함수에 휴게시간 표현도 추가했으면 좋겠습니다

**Comment by qlswltjdhandong** [comment]
그리고 사람의 이름을 입력하면 그 사람의 상세한 근무현황을 보여주는 함수를 구현하는 것도 좋을 거 같아요!!

**Comment by Losecow** [comment]
출근인데 퇴근(or 퇴근인데 출근)을 찍었을 경우 or 출근만(or 퇴근만) 두 번 찍었을 경우 잘못 찍었다고 표현해주는 함수

**Comment by Losecow** [comment]
지각한 사람 체크하는 함수와 사람의 상세한 근무현황을 보여주는 함수를 하나의 검색함수로 합치면 좋을 것 같습니다 (ex. 메뉴에서 검색함수 실행시 1.지각자 조회 2.이름 검색 3.~~ 4.~~)

**Comment by Losecow** [comment]
급여정산 환경 (아르바이트 환경에서 사용될 경우 필요한 기능) 근무한 시간 * 시급 결과 알려주는 함수

**Comment by Losecow** [comment]
*환경 -> 함수

**Comment by qlswltjdhandong** [comment]
1. 출근관련 전체메뉴 불러오는 함수
2. 출근 인증하는 함수
3. 퇴근 인증하는 함수
4. 출근 기록,퇴근 기록 보는 함수(로그)
5. 상태 표시 함수
6. 근무현황(이름을 검색하면 그 사람관련해서 다뜸)--> 검색
7. 출근하고 퇴근 잘못 찍었을 때 표현해주는 함수
8. 지각한 사람 체크 --> 검색
9. 급여정산 함수(아르바이트 경우) --> 검색

**Comment by qlswltjdhandong** [comment]
일단은 정리를 해봤고요

**Comment by qlswltjdhandong** [comment]
그 뭐지 기본적인 사람 추가하고 삭제하는 것도 들어가야 될 거 같아요

**Comment by Losecow** [comment]
넹~~

**Comment by qlswltjdhandong** [comment]
CUD 기능, 데이터 파일 저장/읽어오기 도 넣어야 될 거 같아요

**Comment by Losecow** [comment]
사용자 정보 업데이트 함수도 있어야 할 것 같습니다

**Comment by Losecow** [comment]
넵넵

**Comment by qlswltjdhandong** [comment]
사람 추가하는 함수
사람을 삭제하는 함수
사람을 수정하는 함수
데이터 파일 저장
데이터 파일 읽어오기
출근관련 전체메뉴 불러오는 함수
출근 인증하는 함수
퇴근 인증하는 함수
출근 기록,퇴근 기록 보는 함수(로그)
상태 표시 함수
근무현황(이름을 검색하면 그 사람관련해서 다뜸)--> 검색
출근하고 퇴근 잘못 찍었을 때 표현해주는 함수
지각한 사람 체크 --> 검색
급여정산 함수(아르바이트 경우) --> 검색
