### ISSUE TITLE
사람정보를 삭제하는 함수

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastleminiproject1#5]

**Comment by qlswltjdhandong** [comment]
이 함수의 경우에 우리가 4개의 정보를 입력을 받잖아요
이름 나이 직책 전화번호 이 4개 그래서 나이를 -1로 하면 되지 않을 까요?

**Comment by qlswltjdhandong** [comment]
기준을 나이로 하는거죠!!

**Comment by Losecow** [comment]
네네 나이가 -1 일 때 출력되지 않게 하는 방향으로 하면 좋을거같아요
