### ISSUE TITLE
4. 데이터 파일 저장

### ISSUE THREAD

**Issue by qlswltjdhandong** [cowcastle/cowcastleminiproject1#7]

**Comment by qlswltjdhandong** [comment]
어떤 데이터를 파일에 저장을 시킬까요?

**Comment by Losecow** [comment]
출근이나 퇴근이 찍힐 시 자동으로 저장되게 하는 건 어떤가요?

**Comment by qlswltjdhandong** [comment]
아 그러면 갑자기 시스템이 종료되거나 하는 상황에서 데이터 유실을 막을 수 있겠네요

**Comment by Losecow** [comment]
사용자 정보는 영구히 저장되게 하고 출퇴근 기록만 따로 계속 저장되게 했으면 좋겠어요

**Comment by qlswltjdhandong** [comment]
출근시간하고 퇴근시간을 나타내는 함수를 따로 만들어서 이 함수 안에서 실행되게 하면 될 거 같아요!!
https://korbillgates.tistory.com/100

**Comment by qlswltjdhandong** [comment]
사용자 정보 출근 시간 퇴근시간
빈지성         10시       11시
니깐 굳이 안 나눠도 될 거 같아요

**Comment by Losecow** [comment]
아 이해했습니다 !

**Comment by Losecow** [comment]
출근 함수에 맞춰 저장 함수가 바로 실행되게 하면 될거같아요

**Comment by qlswltjdhandong** [comment]
네네!! 좋습니다!!

**Comment by qlswltjdhandong** [comment]
그리고 퇴근할때도요!!

**Comment by Losecow** [comment]
아아 넵넵!!

**Comment by qlswltjdhandong** [comment]
그리면 정리를 해볼게요!!

**Comment by qlswltjdhandong** [comment]
데이터 정보를 저장하는 함수를 출퇴근 인증하는 함수가 실행될때마다 실행을 하게 되는 거고
데이터가 현재시간이기 때문에 위에 링크에 있는 함수를 구현해서 그 값을 받아와서 특정 자리에다가 넣으면 될 거 같습니다!!

**Comment by Losecow** [comment]
넵 정리 감사합니다~!~
