### ISSUE TITLE
6. 출근관련 전체메뉴 불러오는 함수

### ISSUE THREAD

**Issue by Losecow** [cowcastle/cowcastleminiproject1#9]

**Comment by Losecow** [comment]
이건 간단하게 지난 과제에 사용됐던 방식으로 진행하면 좋을거같아요

**Comment by qlswltjdhandong** [comment]
1. 정보 추가
2. 정보 수정
3. 정보 삭제
4. 출근 인증
약간 이런식으로 나타낼 수 있도록 코드 짜고
각각의 함수가 실행되고 끝날 때마다 보여주면 좋을 거 같아요!!

**Comment by Losecow** [comment]
넵넵~!~
